version: '3.8'

services:
  # Your Django application
  appseed-app:
    build: .
    environment:
      - .env  # Reference environment variables from .env file
    volumes:
      - ./project:/app  # Mount your project directory to /app

  # Postgres database
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newsand
      POSTGRES_DB: berry
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data volume

  # Nginx reverse proxy
  nginx:
    image: nginx:latest
    ports:
      - "80:8000"  # Expose port 80 on host, forward to port 8000 (default for Django) in appseed-app container
    volumes:
      - ./nginx:/etc/nginx/conf.d  # Mount your Nginx configuration
    depends_on:
      - appseed-app  # Wait for appseed-app to be ready

volumes:
  postgres_data: {}
