# Generated by Django 4.2.9 on 2024-03-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_album_picture_cover_picture_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='arquivo',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='titulo',
            new_name='title',
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
