# Generated by Django 4.2.9 on 2024-03-19 01:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_titulo_album_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitevars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('page', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
