# Generated by Django 4.2.9 on 2024-03-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sitevars'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevars',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
