# Generated by Django 4.2.9 on 2024-03-23 02:19

from django.db import migrations, models

def set_private_to_false(apps, schema_editor):
    Album = apps.get_model('home', 'Album')  # Replace 'my_app' with your app name
    Album.objects.filter(private__isnull=True).update(private=False)

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_sitevars_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_private_to_false),
    ]
